### PR TITLE
Implements Select with Top

### LINKED ISSUE #28: Select with Top
## Expected Behavior
to be possible create a query with Top:

`Select().Top(2).Fom("table")`

## Actual Behavior
feature not implemented

### PR DESCRIPTION
**Pull request by renant**
Closes #28

### CODE REVIEW

**Comment by renant** [comment]
@AlbertoMonteiro Sorry, it's the first time I'm getting contributing so I was kind of lost. Thank you!

**Comment by AlbertoMonteiro** [comment]
Np @renant fell free to ask anything!

**Comment by nicolastakashi** [comment]
Thank you very much for your contribution.

**Comment by reinaldocoelho** [comment]
@all we will consider other databases beyond of MSSQL ?
Because TOP is only to MSSQL, MySql for example uses Limit on the end of query.

**Comment by AlbertoMonteiro** [comment]
Nice question @reinaldocoelho, I belive that most users of this library use dapper, that targets officialy only  SQL Server. But we use extensions methods to create the query, so its easy to make your own command method. 
This is not a final answer about supporting only SQL Server, we can figure out about this.

**Comment by gustavoferrazfontes** [comment]
@reinaldocoelho we thought about this question, but for a MVP release we decided to start with SQL Server, just for that.

**Comment by reinaldocoelho** [comment]
Could be interesting to put this information in README.md, what you think?
I can send a pull request if its true :-)

**Pull request merged**
